name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "We're glad you've opened your first issue. Please provide all the necessary details and any relevant code or screenshots to help us understand the problem better. Our team will review your issue and provide assistance as soon as possible. Thank you for contributing!"
          pr-message: "Congratulations on your first pull request! We appreciate your effort in contributing to the repository. Please ensure that your pull request includes a clear description of the changes you've made and any related issue numbers. Our team will review your pull request and provide feedback. Thank you for your valuable contribution!"
