apiVersion: v1
kind: Service
metadata:
  name: metatrader
spec:
  selector:
    app: metatrader
  ports:
    - name: vnc
      port: 5900
    - name: novnc
      port: 5901
    - name: server
      port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metatrader
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: metatrader
  template:
    metadata:
      labels:
        app: metatrader
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: metatrader
          image: {{ .Values.images.metatrader }}
          ports:
            - containerPort: 5900
            - containerPort: 5901
            - containerPort: 8000
          env:
            - name: MT5_LOGIN
              value: "{{ .Values.env.metatrader.MT5_LOGIN }}"
            - name: MT5_PASSWORD
              value: "{{ .Values.env.metatrader.MT5_PASSWORD }}"
            - name: MT5_SERVER
              value: "{{ .Values.env.metatrader.MT5_SERVER }}"
            - name: MT_FILES_DIR
              value: "{{ .Values.env.metatrader.MT_FILES_DIR }}"
            - name: DATABASE_URL
              value: "{{ .Values.env.metatrader.DATABASE_URL }}"
