name: Deploy MetaTrader 5 Terminal (REST API)

on:
  push:
    branches:
      - "legacy/terminal-server"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: metatrader-5/
          file: metatrader-5/Dockerfile.mt5
          platforms: linux/amd64
          push: true
          tags: fortesenselabs/metatrader-rest:lastest,fortesenselabs/metatrader-rest:5
